version: '3.7'
services:
 
# db: 
#    environment:
#      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
    volumes:
      - db_data:/var/lib/postgres/data

  backend:
    image: phisit11/nginx-golang:0227
    volumes:
      - static_data:/usr/src/app/static
    networks:
      - webproxy
      - default
    depends_on:
      - db  
    deploy:
      replicas: 1
      labels:
        - traefik.docker.network=webproxy
        - traefik.enable=true
        - traefik.constraint-label=webproxy
        - traefik.http.routers.${APPNAME}-https.entrypoints=websecure
        - traefik.http.routers.${APPNAME}-https.rule=Host("${APPNAME}.xops.ipv9.me")
        - traefik.http.routers.${APPNAME}-https.tls.certresolver=defauit
        - traefik.http.services.${APPNAME}.loadbalancer.server.port=80
      restart_policy:
        condition: any
      update_config:
        delay: 5s

      
volumes:
    static_data:
    db_data:

networks:
    default:
      driver: overlay
    webproxy:
      external: true
