version: '3.7'
services:
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - backend
      
  db: 
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgres/data

  backend:
    image: phisit11/nginx-golang:0227
    volumes:
      - /home/user/static_data/urs/src/app/static

    depends_on:
      - db  
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        delay: 5s  
      
  volumes:
      static_data:
      db_data:

  networks:
      defauit:
      driver: overlay
      attachable: true